"use client";
import { FormEvent,useState } from "react";
import { useRouter } from "next/navigation";
type Proveedor={id:string;nombre:string};type Opcion={productoId:string;varianteId:string|null;etiqueta:string};
const campo="mt-2 min-h-11 w-full rounded-xl border border-zinc-700 bg-black px-4 text-white outline-none focus:border-lime-400";

export function ReglaForm({proveedores,opciones}:{proveedores:Proveedor[];opciones:Opcion[]}){
  const router=useRouter();const [tipo,setTipo]=useState("porcentaje");const [error,setError]=useState("");const [guardando,setGuardando]=useState(false);
  async function guardar(e:FormEvent<HTMLFormElement>){e.preventDefault();setGuardando(true);setError("");const formulario=e.currentTarget;const f=new FormData(formulario);const [producto_id,variante_id]=String(f.get("producto")||"").split("|");const r=await fetch("/api/admin/comisiones/reglas",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({proveedor_id:f.get("proveedor_id"),producto_id,variante_id:variante_id||null,tipo,valor:f.get("valor")})});const j=await r.json().catch(()=>null) as {error?:string}|null;setGuardando(false);if(!r.ok){setError(j?.error||"No fue posible guardar.");return;}formulario.reset();router.refresh()}
  return <form onSubmit={guardar} className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm text-zinc-300">Proveedor<select required name="proveedor_id" defaultValue="" className={campo}><option value="" disabled>Selecciona un proveedor</option>{proveedores.map(p=><option key={p.id} value={p.id}>{p.nombre}</option>)}</select></label><label className="text-sm text-zinc-300">Producto o variante<select required name="producto" defaultValue="" className={campo}><option value="" disabled>Selecciona el producto exacto</option>{opciones.map(o=><option key={`${o.productoId}|${o.varianteId||""}`} value={`${o.productoId}|${o.varianteId||""}`}>{o.etiqueta}</option>)}</select></label><label className="text-sm text-zinc-300">Forma de cálculo<select value={tipo} onChange={e=>setTipo(e.target.value)} className={campo}><option value="porcentaje">Porcentaje de la venta</option><option value="valor_fijo">Valor fijo por unidad</option></select></label><label className="text-sm text-zinc-300">{tipo==="porcentaje"?"Porcentaje":"Valor por unidad"}<input required name="valor" type="number" min="0" max={tipo==="porcentaje"?100:undefined} step="0.01" className={campo}/></label>{error&&<p role="alert" className="font-bold text-red-300 sm:col-span-2">{error}</p>}<button disabled={guardando} className="min-h-11 rounded-xl bg-lime-400 px-5 font-black text-black disabled:opacity-50 sm:col-span-2">{guardando?"Guardando...":"Guardar regla de comisión"}</button></form>
}

export function LiquidacionForm({proveedores}:{proveedores:Proveedor[]}){
  const router=useRouter();const hoy=new Date().toISOString().slice(0,10);const primerDia=`${hoy.slice(0,8)}01`;const [error,setError]=useState("");const [guardando,setGuardando]=useState(false);
  async function guardar(e:FormEvent<HTMLFormElement>){e.preventDefault();setGuardando(true);setError("");const f=new FormData(e.currentTarget);const r=await fetch("/api/admin/comisiones/liquidaciones",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(f))});const j=await r.json().catch(()=>null) as {error?:string;id?:string}|null;setGuardando(false);if(!r.ok){setError(j?.error||"No fue posible liquidar.");return;}router.push(`/admin/comisiones/${j?.id}`);router.refresh()}
  return <form onSubmit={guardar} className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm text-zinc-300 sm:col-span-2">Proveedor<select required name="proveedor_id" defaultValue="" className={campo}><option value="" disabled>Selecciona un proveedor</option>{proveedores.map(p=><option key={p.id} value={p.id}>{p.nombre}</option>)}</select></label><label className="text-sm text-zinc-300">Desde<input required name="fecha_inicio" type="date" defaultValue={primerDia} className={campo}/></label><label className="text-sm text-zinc-300">Hasta<input required name="fecha_fin" type="date" defaultValue={hoy} className={campo}/></label><label className="text-sm text-zinc-300 sm:col-span-2">Notas<input name="notas" placeholder="Ejemplo: liquidación de la primera quincena" className={campo}/></label>{error&&<p role="alert" className="font-bold text-red-300 sm:col-span-2">{error}</p>}<button disabled={guardando} className="min-h-11 rounded-xl bg-lime-400 px-5 font-black text-black disabled:opacity-50 sm:col-span-2">{guardando?"Calculando...":"Generar liquidación"}</button></form>
}
