import Link from "next/link";
import { requireAdmin } from "@/app/lib/adminAuth";
import { supabaseAdmin } from "@/app/lib/supabaseAdmin";
import { LiquidacionForm,ReglaForm } from "./ComisionesForm";
export const dynamic="force-dynamic";
const dinero=new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0});
type Proveedor={id:string;nombre:string};
export default async function ComisionesPage(){await requireAdmin();const [{data:proveedores},{data:productos},{data:variantes},{data:reglas,error},{data:liquidaciones}]=await Promise.all([supabaseAdmin.from("proveedores").select("id,nombre").eq("activo",true).order("nombre"),supabaseAdmin.from("productos").select("id,nombre,sku").eq("activo",true).order("nombre"),supabaseAdmin.from("variantes_producto").select("id,producto_id,nombre,sku").eq("activo",true).order("nombre"),supabaseAdmin.from("reglas_comision_proveedor").select("id,tipo,valor,activo,proveedores(nombre),productos(nombre),variantes_producto(nombre)").order("creado_en",{ascending:false}),supabaseAdmin.from("liquidaciones_comision").select("id,consecutivo,fecha_inicio,fecha_fin,estado,ventas_netas,total_comision,proveedores(nombre)").order("creado_en",{ascending:false}).limit(100)]);
  const ps=(proveedores||[]) as Proveedor[];const variantesPorProducto=new Map<string,typeof variantes>();for(const v of variantes||[]){const a=variantesPorProducto.get(v.producto_id)||[];a.push(v);variantesPorProducto.set(v.producto_id,a)}const opciones=(productos||[]).flatMap(p=>{const vs=variantesPorProducto.get(p.id)||[];return vs.length?vs.map(v=>({productoId:p.id,varianteId:v.id,etiqueta:`${p.nombre} · ${v.nombre} (${v.sku})`})):[{productoId:p.id,varianteId:null,etiqueta:`${p.nombre} (${p.sku||"sin SKU"})`}]});const pendientes=(liquidaciones||[]).filter(l=>["borrador","revisada"].includes(l.estado));const pagado=(liquidaciones||[]).filter(l=>l.estado==="pagada").reduce((s,l)=>s+Number(l.total_comision),0);
  return <main className="mx-auto max-w-7xl px-5 py-8"><p className="text-xs font-black uppercase tracking-[.24em] text-lime-400">ALIADOS COMERCIALES</p><h1 className="mt-2 text-3xl font-black">Comisiones de proveedores</h1><p className="mt-2 text-sm text-zinc-400">Calcula lo causado por ventas reales, descuenta devoluciones y conserva el comprobante del pago.</p>
    {error?<div className="mt-7 rounded-2xl border border-amber-500/30 bg-amber-950/20 p-5 text-amber-200"><p className="font-black">Falta activar este módulo</p><p className="mt-1 text-sm">Ejecuta una sola vez activar_comisiones_proveedores.sql en Supabase.</p></div>:<>
    <section className="mt-7 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-5"><p className="text-sm text-zinc-400">Reglas activas</p><p className="mt-2 text-3xl font-black">{(reglas||[]).filter(r=>r.activo).length}</p></div><div className="rounded-2xl border border-amber-500/25 bg-amber-950/20 p-5"><p className="text-sm text-amber-200">Liquidaciones pendientes</p><p className="mt-2 text-3xl font-black text-amber-300">{pendientes.length}</p></div><div className="rounded-2xl border border-lime-500/25 bg-lime-950/20 p-5"><p className="text-sm text-lime-200">Comisiones pagadas</p><p className="mt-2 text-3xl font-black text-lime-300">{dinero.format(pagado)}</p></div></section>
    <div className="mt-7 grid items-start gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-zinc-800 bg-zinc-900 p-6"><h2 className="text-xl font-black">Configurar comisión</h2><p className="mt-1 text-sm text-zinc-400">Asigna quién recibe comisión por cada producto o variante.</p><ReglaForm proveedores={ps} opciones={opciones}/></section><section className="rounded-2xl border border-zinc-800 bg-zinc-900 p-6"><h2 className="text-xl font-black">Nueva liquidación</h2><p className="mt-1 text-sm text-zinc-400">Solo incluye ventas pagadas que todavía no hayan sido liquidadas.</p><LiquidacionForm proveedores={ps}/></section></div>
    <section className="mt-7 overflow-hidden rounded-2xl border border-zinc-800"><div className="bg-zinc-900 px-6 py-5"><h2 className="text-xl font-black">Liquidaciones</h2></div>{liquidaciones?.length?<div className="divide-y divide-zinc-800">{liquidaciones.map(l=>{const p=Array.isArray(l.proveedores)?l.proveedores[0]:l.proveedores as {nombre?:string}|null;return <article key={l.id} className="flex flex-wrap items-center gap-4 p-5"><div><strong>LIQ-{String(l.consecutivo).padStart(5,"0")}</strong><p className="mt-1 text-sm text-zinc-400">{p?.nombre} · {l.fecha_inicio} a {l.fecha_fin}</p></div><span className="ml-auto rounded-full bg-zinc-800 px-3 py-1 text-xs font-black uppercase text-lime-300">{l.estado}</span><div className="text-right"><p className="text-xs text-zinc-500">Comisión</p><strong>{dinero.format(Number(l.total_comision))}</strong></div><Link href={`/admin/comisiones/${l.id}`} className="rounded-xl border border-zinc-700 px-4 py-2 font-bold hover:border-lime-400">Ver detalle</Link></article>})}</div>:<p className="p-7 text-zinc-400">Todavía no hay liquidaciones.</p>}</section>
    <section className="mt-7 overflow-hidden rounded-2xl border border-zinc-800"><div className="bg-zinc-900 px-6 py-5"><h2 className="text-xl font-black">Reglas configuradas</h2></div>{reglas?.length?<div className="divide-y divide-zinc-800">{reglas.map(r=>{const pr=Array.isArray(r.proveedores)?r.proveedores[0]:r.proveedores as {nombre?:string}|null;const prod=Array.isArray(r.productos)?r.productos[0]:r.productos as {nombre?:string}|null;const vari=Array.isArray(r.variantes_producto)?r.variantes_producto[0]:r.variantes_producto as {nombre?:string}|null;return <div key={r.id} className="flex flex-wrap justify-between gap-3 p-5"><span><strong>{pr?.nombre}</strong><small className="ml-2 text-zinc-400">{prod?.nombre}{vari?.nombre?` · ${vari.nombre}`:""}</small></span><strong className="text-lime-300">{r.tipo==="porcentaje"?`${Number(r.valor).toLocaleString("es-CO")}%`: `${dinero.format(Number(r.valor))} por unidad`}</strong></div>})}</div>:<p className="p-7 text-zinc-400">Todavía no hay reglas.</p>}</section></>}
  </main>}
