"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

const opciones:Record<string,{estado:string;texto:string;inventario?:boolean}[]>={solicitada:[{estado:"aprobada",texto:"Aprobar caso"},{estado:"rechazada",texto:"Rechazar caso"}],aprobada:[{estado:"recibida",texto:"Marcar mercancía recibida",inventario:true},{estado:"reembolsada",texto:"Registrar reembolso"},{estado:"cerrada",texto:"Cerrar sin reintegrar"}],recibida:[{estado:"reembolsada",texto:"Registrar reembolso"},{estado:"cerrada",texto:"Cerrar caso"}],reembolsada:[{estado:"cerrada",texto:"Cerrar caso"}]};
export default function GestionDevolucion({id,estado,valor}:{id:string;estado:string;valor:number}){const router=useRouter();const [seleccion,setSeleccion]=useState(opciones[estado]?.[0]?.estado||"");const [guardando,setGuardando]=useState(false);const [error,setError]=useState("");const actual=opciones[estado]||[];
  async function guardar(e:FormEvent<HTMLFormElement>){e.preventDefault();setGuardando(true);setError("");const f=new FormData(e.currentTarget);const opt=actual.find(o=>o.estado===seleccion);const respuesta=await fetch(`/api/admin/devoluciones/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({estado:seleccion,nota:f.get("nota"),metodo_reembolso:f.get("metodo_reembolso"),referencia_reembolso:f.get("referencia_reembolso"),reintegrar_inventario:opt?.inventario&&f.get("reintegrar")==="si"})});const resultado=await respuesta.json().catch(()=>null) as {error?:string}|null;setGuardando(false);if(!respuesta.ok){setError(resultado?.error||"No fue posible actualizar el caso.");return;}router.refresh();}
  if(!actual.length)return <p className="mt-4 text-sm text-zinc-400">Este caso ya no admite cambios.</p>;
  const campo="mt-2 min-h-11 w-full rounded-xl border border-zinc-700 bg-black px-4 text-white outline-none focus:border-lime-400";
  return <form onSubmit={guardar} className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm text-zinc-300">Siguiente acción<select value={seleccion} onChange={e=>setSeleccion(e.target.value)} className={campo}>{actual.map(o=><option key={o.estado} value={o.estado}>{o.texto}</option>)}</select></label>
    {seleccion==="recibida"&&<label className="text-sm text-zinc-300">Inventario<select name="reintegrar" className={campo}><option value="no">No reintegrar (dañado o no vendible)</option><option value="si">Sí, devolver unidades al inventario</option></select></label>}
    {seleccion==="reembolsada"&&<><label className="text-sm text-zinc-300">Medio del reembolso<input required name="metodo_reembolso" placeholder="Transferencia, reversión Wompi..." className={campo}/></label><label className="text-sm text-zinc-300">Referencia<input name="referencia_reembolso" placeholder="Número o comprobante" className={campo}/></label><p className="text-sm text-zinc-400 sm:col-span-2">Valor registrado para devolver: <strong className="text-white">{new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0}).format(valor)}</strong></p></>}
    <label className="text-sm text-zinc-300 sm:col-span-2">Nota del movimiento<textarea name="nota" rows={3} placeholder="Deja evidencia de la decisión o conversación con el cliente" className={`${campo} py-3`}/></label>{error&&<p role="alert" className="font-bold text-red-300 sm:col-span-2">{error}</p>}<button disabled={guardando} className="min-h-11 rounded-xl bg-lime-400 px-5 font-black text-black disabled:opacity-50 sm:col-span-2">{guardando?"Guardando...":"Confirmar acción"}</button></form>}
