import Link from "next/link";
import { notFound } from "next/navigation";
import { requireAdmin } from "@/app/lib/adminAuth";
import { supabaseAdmin } from "@/app/lib/supabaseAdmin";
import GestionDevolucion from "./GestionDevolucion";

export const dynamic="force-dynamic";
const dinero=new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0});
const texto:Record<string,string>={solicitada:"Solicitada",aprobada:"Aprobada",rechazada:"Rechazada",recibida:"Recibida",reembolsada:"Reembolsada",cerrada:"Cerrada",devolucion:"Devolución",garantia:"Garantía",reembolso:"Reembolso"};
export default async function DevolucionDetalle({params}:{params:Promise<{id:string}>}){await requireAdmin();const {id}=await params;const [{data:caso,error},{data:productos},{data:historial}]=await Promise.all([supabaseAdmin.from("devoluciones").select("*,pedidos(id,numero_pedido,comprador_nombre,comprador_correo,comprador_telefono,total)").eq("id",id).maybeSingle(),supabaseAdmin.from("productos_devolucion").select("*").eq("devolucion_id",id).order("id"),supabaseAdmin.from("historial_devoluciones").select("*").eq("devolucion_id",id).order("creado_en",{ascending:false})]);if(error||!caso)notFound();const pedido=Array.isArray(caso.pedidos)?caso.pedidos[0]:caso.pedidos;
  return <main className="mx-auto max-w-5xl px-5 py-8"><Link href="/admin/devoluciones" className="font-bold text-lime-400">← Volver a devoluciones</Link><section className="mt-5 rounded-2xl border border-zinc-800 bg-zinc-900 p-6"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.2em] text-lime-400">{texto[caso.tipo]||caso.tipo}</p><h1 className="mt-2 text-3xl font-black">{caso.numero}</h1><Link href={`/admin/pedidos/${pedido?.id}`} className="mt-2 inline-block text-sm text-zinc-400 hover:text-lime-300">{pedido?.numero_pedido} · {pedido?.comprador_nombre}</Link></div><span className="h-fit rounded-full bg-lime-400/15 px-4 py-2 font-black text-lime-300">{texto[caso.estado]||caso.estado}</span></div><dl className="mt-6 grid gap-5 sm:grid-cols-3"><div><dt className="text-sm text-zinc-500">Motivo</dt><dd className="mt-1 font-bold">{caso.motivo}</dd></div><div><dt className="text-sm text-zinc-500">Valor previsto</dt><dd className="mt-1 font-black text-lime-400">{dinero.format(Number(caso.valor_reembolso))}</dd></div><div><dt className="text-sm text-zinc-500">Inventario</dt><dd className="mt-1 font-bold">{caso.inventario_reintegrado_en?"Reintegrado":"Sin reintegrar"}</dd></div></dl>{caso.detalle&&<p className="mt-5 rounded-xl bg-black/40 p-4 text-sm text-zinc-300">{caso.detalle}</p>}</section>
    <section className="mt-5 overflow-hidden rounded-2xl border border-zinc-800"><h2 className="bg-zinc-900 px-6 py-4 text-xl font-black">Productos afectados</h2><div className="divide-y divide-zinc-800">{(productos||[]).map(p=><div key={p.id} className="flex justify-between gap-4 px-6 py-4"><span><strong>{p.nombre}</strong>{p.variante_nombre&&<small className="ml-2 text-lime-400">{p.variante_nombre}</small>}</span><strong>{p.cantidad} unidad{p.cantidad===1?"":"es"}</strong></div>)}</div></section>
    <section className="mt-5 rounded-2xl border border-zinc-800 bg-zinc-900 p-6"><h2 className="text-xl font-black">Gestionar caso</h2><p className="mt-2 text-sm text-zinc-400">Los cambios quedan registrados y solo se permiten en el orden correcto.</p><GestionDevolucion key={caso.estado} id={caso.id} estado={caso.estado} valor={Number(caso.valor_reembolso)}/></section>
    <section className="mt-5 rounded-2xl border border-zinc-800 bg-zinc-900 p-6"><h2 className="text-xl font-black">Historial</h2><div className="mt-4 space-y-3">{(historial||[]).map(h=><div key={h.id} className="rounded-xl border border-zinc-800 bg-black/30 p-4"><div className="flex justify-between gap-4"><strong>{texto[h.estado_nuevo]||h.estado_nuevo}</strong><time className="text-xs text-zinc-500">{new Date(h.creado_en).toLocaleString("es-CO")}</time></div>{h.nota&&<p className="mt-2 text-sm text-zinc-400">{h.nota}</p>}</div>)}</div></section></main>}
