import Link from "next/link";
import { requireAdmin } from "@/app/lib/adminAuth";
import { supabaseAdmin } from "@/app/lib/supabaseAdmin";

export const dynamic="force-dynamic";
const dinero=new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0});
const textos:Record<string,string>={solicitada:"Solicitada",aprobada:"Aprobada",rechazada:"Rechazada",recibida:"Recibida",reembolsada:"Reembolsada",cerrada:"Cerrada",devolucion:"Devolución",garantia:"Garantía",reembolso:"Reembolso"};
export default async function DevolucionesPage(){
  await requireAdmin();
  const {data,error}=await supabaseAdmin.from("devoluciones").select("id,numero,tipo,estado,motivo,valor_reembolso,creado_en,pedidos(numero_pedido,comprador_nombre)").order("creado_en",{ascending:false}).limit(200);
  const casos=data||[];const abiertos=casos.filter(c=>!["rechazada","cerrada"].includes(c.estado)).length;const pendientes=casos.filter(c=>["solicitada","aprobada"].includes(c.estado)).length;const valor=casos.filter(c=>c.estado==="reembolsada").reduce((s,c)=>s+Number(c.valor_reembolso),0);
  return <main className="mx-auto max-w-7xl px-5 py-8">
    <p className="text-xs font-black uppercase tracking-[0.24em] text-lime-400">POSVENTA</p><h1 className="mt-2 text-3xl font-black">Devoluciones y garantías</h1><p className="mt-2 text-sm text-zinc-400">Control de casos, mercancía recibida y dinero reembolsado.</p>
    {error?<div className="mt-7 rounded-2xl border border-amber-700/50 bg-amber-950/30 p-5 text-amber-200"><p className="font-bold">El módulo todavía no está activado.</p><p className="mt-1 text-sm">Ejecuta una sola vez el archivo activar_devoluciones.sql en Supabase.</p></div>:<>
      <section className="mt-7 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-5"><p className="text-sm text-zinc-400">Casos abiertos</p><p className="mt-2 text-3xl font-black">{abiertos}</p></div><div className="rounded-2xl border border-amber-600/30 bg-amber-950/20 p-5"><p className="text-sm text-amber-200/70">Pendientes de atención</p><p className="mt-2 text-3xl font-black text-amber-300">{pendientes}</p></div><div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-5"><p className="text-sm text-zinc-400">Total reembolsado</p><p className="mt-2 text-3xl font-black text-lime-400">{dinero.format(valor)}</p></div></section>
      {casos.length?<div className="mt-7 overflow-x-auto rounded-2xl border border-zinc-800"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-zinc-900 text-xs uppercase text-zinc-500"><tr><th className="px-5 py-4">Caso</th><th className="px-5 py-4">Pedido y cliente</th><th className="px-5 py-4">Motivo</th><th className="px-5 py-4">Estado</th><th className="px-5 py-4 text-right">Valor</th><th className="px-5 py-4"></th></tr></thead><tbody className="divide-y divide-zinc-800">{casos.map(c=>{const pedido=Array.isArray(c.pedidos)?c.pedidos[0]:c.pedidos as {numero_pedido?:string;comprador_nombre?:string}|null;return <tr key={c.id}><td className="px-5 py-4"><strong>{c.numero}</strong><small className="mt-1 block text-lime-400">{textos[c.tipo]||c.tipo}</small></td><td className="px-5 py-4"><strong>{pedido?.numero_pedido||"—"}</strong><small className="mt-1 block text-zinc-500">{pedido?.comprador_nombre||"—"}</small></td><td className="max-w-xs px-5 py-4 text-zinc-300">{c.motivo}</td><td className="px-5 py-4"><span className="rounded-full bg-zinc-800 px-3 py-1 font-bold text-lime-300">{textos[c.estado]||c.estado}</span></td><td className="px-5 py-4 text-right font-black">{dinero.format(Number(c.valor_reembolso))}</td><td className="px-5 py-4 text-right"><Link href={`/admin/devoluciones/${c.id}`} className="rounded-xl border border-zinc-700 px-4 py-2 font-bold hover:border-lime-400">Gestionar</Link></td></tr>})}</tbody></table></div>:<p className="mt-7 rounded-2xl border border-zinc-800 bg-zinc-900 p-8 text-center text-zinc-400">Aún no hay casos. Puedes crear uno desde el detalle de cualquier pedido.</p>}
    </>}
  </main>;
}
